name: "Workflow Dispatch"
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  call-build:
    name: "Build"
    needs: call-lint
    uses: ./.github/workflows/build.yml
    secrets: inherit

  call-test:
    name: "Test"
    needs: call-build
    uses: ./.github/workflows/test.yml
    secrets: inherit
